---
apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
product: kind
registry: kube-apiserver-proxy-kind-registry
kindV1Alpha4Cluster:
  name: kube-apiserver-proxy-kind
  nodes:
    - role: control-plane
      image: kindest/node:v1.27.1
      extraPortMappings:
        - containerPort: 30080
          hostPort: 80
          protocol: TCP
        - containerPort: 30443
          hostPort: 443
          protocol: TCP
